//files
export const LOAD_FILES = 'LOAD_FILES';
export const LOAD_SAMPLE_FILE = 'LOAD_SAMPLE_FILE';
export const CANCEL_FILE_ACTIONS = 'CANCEL_FILE_ACTIONS';
export const FILE_ERROR = 'FILE_ERROR';
export const REQUEST_DSV_COLUMN_MAPPING = 'REQUEST_DSV_COLUMN_MAPPING';
export const REQUEST_GEOJSON_NAME_FIELD = 'REQUEST_GEOJSON_NAME_FIELD';

export const SET_FIELDS_TO_COLUMNS_MAPPING = 'SET_FIELDS_TO_COLUMNS_MAPPING';
export const SET_FEATURE_NAME_FIELD = 'SET_FEATURE_NAME_FIELD';

export const ADD_SPECIES_AND_BINS = 'ADD_SPECIES_AND_BINS';

//progress
export const FILE_PROGRESS = 'FILE_PROGRESS';
export const BINNING_PROGRESS = 'BINNING_PROGRESS';
export const CLUSTERING_PROGRESS = 'CLUSTERING_PROGRESS';

//errorMessage
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

//worldmap
export const CHANGE_PROJECTION = 'CHANGE_PROJECTION';
export const LOAD_WORLD = 'LOAD_WORLD';
export const ADD_WORLD = 'ADD_WORLD';
export const CHANGE_GRATICULE_STEP = 'CHANGE_GRATICULE_STEP';
export const CHANGE_CLIP_TO_LAND = 'CHANGE_CLIP_TO_LAND';
export const CHANGE_SHOW_CELL_BORDERS = 'CHANGE_SHOW_CELL_BORDERS';

//infomap
export const GET_CLUSTERS = 'GET_CLUSTERS';
export const CALCULATE_CLUSTERS = 'CALCULATE_CLUSTERS';
export const ADD_CLUSTERS = 'ADD_CLUSTERS';
export const ADD_CLUSTERS_AND_STATISTICS = 'ADD_CLUSTERS_AND_STATISTICS';

//binning
export const BINNING_CHANGE_TYPE = 'BINNING_CHANGE_TYPE';
export const BINNING_MIN_NODE_SIZE = 'BINNING_MIN_NODE_SIZE';
export const BINNING_MAX_NODE_SIZE = 'BINNING_MAX_NODE_SIZE';
export const BINNING_NODE_CAPACITY = 'BINNING_NODE_CAPACITY';
export const BINNING_LOWER_THRESHOLD = 'BINNING_LOWER_THRESHOLD';

//Display
export const CHANGE_GROUP_BY = 'CHANGE_GROUP_BY';
